-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 22:53:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Responsável`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsável` (
  `idResponsavel` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idResponsavel`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecânico`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `idProduto` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Descrição Técnica` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Documento` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Tipo` TINYINT NOT NULL COMMENT 'Tipo Pessoa - Física ou Jurídica',
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Documento_UNIQUE` (`Documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meios Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meios Pagamentos` (
  `idMeios Pagamentos` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Validade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMeios Pagamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Data` DATETIME NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Data Conclusão` DATETIME NOT NULL,
  `Meios Pagamentos_idMeios Pagamentos` INT NOT NULL,
  `Peças_idProduto` INT NOT NULL,
  `Mecânico_idMecânico` INT NOT NULL,
  `Responsável_idResponsavel` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem`, `Meios Pagamentos_idMeios Pagamentos`, `Peças_idProduto`, `Mecânico_idMecânico`, `Responsável_idResponsavel`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Meios Pagamentos1_idx` (`Meios Pagamentos_idMeios Pagamentos` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Peças1_idx` (`Peças_idProduto` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Mecânico1_idx` (`Mecânico_idMecânico` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Responsável1_idx` (`Responsável_idResponsavel` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Meios Pagamentos1`
    FOREIGN KEY (`Meios Pagamentos_idMeios Pagamentos`)
    REFERENCES `mydb`.`Meios Pagamentos` (`idMeios Pagamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Peças1`
    FOREIGN KEY (`Peças_idProduto`)
    REFERENCES `mydb`.`Peças` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecânico`)
    REFERENCES `mydb`.`Mecânico` (`idMecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Responsável1`
    FOREIGN KEY (`Responsável_idResponsavel`)
    REFERENCES `mydb`.`Responsável` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
